# 소비자빅데이터분석 2025-2:
## Practice 2 - 파이썬 기초 실습 2

## 1. 함수 (Functions)

### 함수 정의 및 기본 구조

함수는 특정 작업을 수행하는 코드 블록입니다. 코드를 재사용하고 프로그램을 모듈화하는 데 도움을 줍니다.
```python
def my_function(parameter1, parameter2=0):
    """
    This is a docstring explaining what the function does.

    Args:
        parameter1: The first required parameter.
        parameter2: The second optional parameter with a default value of 0.

    Returns:
        The sum of parameter1 and parameter2.
    """
    result = parameter1 + parameter2
    return result
```
### 함수 호출

```python
output = my_function(5)
print(f"함수 호출 결과 (기본값 사용): {output}")
output_with_param2 = my_function(5, 10)
print(f"함수 호출 결과 (매개변수 2 사용): {output_with_param2}")
```

### 매개변수 (Parameters)

함수 정의 시 입력 값을 받기 위해 사용되는 변수입니다.

### 반환값 (Return Value)

함수가 작업을 완료한 후 결과를 호출자에게 돌려주는 값입니다. `return` 키워드를 사용합니다. `return` 문이 없으면 함수는 `None`을 반환합니다.

### 기본값 매개변수 (Default Parameter Values)

매개변수에 기본값을 할당하여 함수 호출 시 해당 매개변수를 생략할 수 있도록 합니다. 기본값 매개변수는 일반 매개변수 뒤에 정의해야 합니다.

```python
def greet(name, greeting="Hello"):
    """인사말과 함께 이름을 출력하는 함수"""
    print(f"{greeting}, {name}!")

greet("Alice") # 기본값 사용
greet("Bob", "Hi") # 새로운 값 전달
```

In [10]:
def my_function(parameter1, parameter2=0):
    """
    This is a docstring explaining what the function does.

    Args:
        parameter1: The first required parameter.
        parameter2: The second optional parameter with a default value of 0.

    Returns:
        The sum of parameter1 and parameter2.
    """
    result = parameter1 + parameter2
    return result

# 함수 호출
output = my_function(5)
print(f"함수 호출 결과 (기본값 사용): {output}")

output_with_param2 = my_function(5, 10)
print(f"함수 호출 결과 (매개변수 2 사용): {output_with_param2}")

def greet(name, greeting="Hello"):
    """인사말과 함께 이름을 출력하는 함수"""
    print(f"{greeting}, {name}!")

greet("Alice") # 기본값 사용
greet("Bob", "Hi") # 새로운 값 전달

함수 호출 결과 (기본값 사용): 5
함수 호출 결과 (매개변수 2 사용): 15
Hello, Alice!
Hi, Bob!


In [6]:
# 빈칸 채우기 실습

# 아래 함수 정의의 빈칸을 채워, 두 숫자를 곱하는 함수를 완성하세요.
# 함수 이름은 `multiply_numbers`, 두 개의 매개변수는 `num1`, `num2`로 합니다.
# 함수는 두 매개변수의 곱을 반환해야 합니다.

def ______(param1, param2):
    """
    두 숫자를 곱하는 함수

    Args:
        param1: 첫 번째 숫자
        param2: 두 번째 숫자

    Returns:
        두 숫자의 곱
    """
    result = param1 * param2
    return ______

# 함수를 호출하여 결과를 확인하세요. (예: multiply_numbers(4, 5))
# print(multiply_numbers(4, 5))

## 2. 리스트 (Lists)

리스트는 순서가 있는 변경 가능한(mutable) 객체의 모음입니다.

다양한 데이터 타입의 요소를 저장할 수 있습니다.

In [4]:
# 리스트 생성

my_list = [1, 2, 3, 'apple', 'banana']
print(f"새로 생성된 리스트: {my_list}")

# 빈 리스트 생성
empty_list = []
print(f"빈 리스트: {empty_list}")

새로 생성된 리스트: [1, 2, 3, 'apple', 'banana']
빈 리스트: []


In [5]:
# 인덱싱 (Indexing)

# 리스트의 요소는 인덱스를 사용하여 접근할 수 있습니다. 인덱스는 0부터 시작합니다.
first_element = my_list[0]
print(f"첫 번째 요소: {first_element}")

# 음수 인덱싱은 리스트의 끝에서부터 접근합니다. -1은 마지막 요소입니다.
last_element = my_list[-1]
print(f"마지막 요소: {last_element}")

첫 번째 요소: 1
마지막 요소: banana


In [6]:
# 슬라이싱 (Slicing)

# 리스트의 일부를 추출하여 새로운 리스트를 만들 수 있습니다. [start:stop:step] 형식을 사용합니다.
# start는 포함, stop은 포함하지 않습니다.
subset = my_list[1:4]
print(f"인덱스 1부터 3까지의 부분 리스트: {subset}")

# 처음부터 특정 인덱스까지
subset_from_start = my_list[:3]
print(f"처음부터 인덱스 2까지의 부분 리스트: {subset_from_start}")

# 특정 인덱스부터 끝까지
subset_to_end = my_list[2:]
print(f"인덱스 2부터 끝까지의 부분 리스트: {subset_to_end}")

# 전체 리스트 복사
list_copy = my_list[:]
print(f"리스트 복사본: {list_copy}")

# 스텝을 사용하여 건너뛰기
every_other_element = my_list[::2]
print(f"한 칸씩 건너뛴 요소들: {every_other_element}")

인덱스 1부터 3까지의 부분 리스트: [2, 3, 'apple']
처음부터 인덱스 2까지의 부분 리스트: [1, 2, 3]
인덱스 2부터 끝까지의 부분 리스트: [3, 'apple', 'banana']
리스트 복사본: [1, 2, 3, 'apple', 'banana']
한 칸씩 건너뛴 요소들: [1, 3, 'banana']


In [7]:
# 리스트 메서드 (1) (List Methods)

# append(): 리스트의 끝에 요소를 추가합니다.
my_list.append('cherry')
print(f"append 후 리스트: {my_list}")

# remove(): 리스트에서 첫 번째로 발견되는 특정 요소를 제거합니다.
my_list.remove(2)
print(f"remove 후 리스트: {my_list}")

# pop(): 특정 인덱스의 요소를 제거하고 해당 요소를 반환합니다. 인덱스를 지정하지 않으면 마지막 요소를 제거하고 반환합니다.
popped_element = my_list.pop(1) # 인덱스 1 (원래 3이었던 요소) 제거
print(f"pop으로 제거된 요소: {popped_element}")
print(f"pop 후 리스트: {my_list}")

append 후 리스트: [1, 2, 3, 'apple', 'banana', 'cherry']
remove 후 리스트: [1, 3, 'apple', 'banana', 'cherry']
pop으로 제거된 요소: 3
pop 후 리스트: [1, 'apple', 'banana', 'cherry']


In [8]:
# 리스트 메서드 (2) (List Methods)

# len(): 리스트의 길이를 반환합니다.
list_length = len(my_list)
print(f"리스트의 길이: {list_length}")

# extend(): 다른 리스트의 모든 요소를 현재 리스트의 끝에 추가합니다.
another_list = ['date', 'elderberry']
my_list.extend(another_list)
print(f"extend 후 리스트: {my_list}")

# insert(): 특정 인덱스에 요소를 삽입합니다.
my_list.insert(1, 'blueberry')
print(f"insert 후 리스트: {my_list}")

리스트의 길이: 4
extend 후 리스트: [1, 'apple', 'banana', 'cherry', 'date', 'elderberry']
insert 후 리스트: [1, 'blueberry', 'apple', 'banana', 'cherry', 'date', 'elderberry']


In [9]:
# 리스트 메서드 (3) (List Methods)

# index(): 특정 값의 첫 번째 인덱스를 반환합니다.
index_of_apple = my_list.index('apple')
print(f"'apple'의 인덱스: {index_of_apple}")

# count(): 특정 값의 개수를 반환합니다.
my_list.append('apple')
count_of_apple = my_list.count('apple')
print(f"'apple'의 개수: {count_of_apple}")

# sort(): 리스트를 정렬합니다 (제자리 정렬).
numbers = [3, 1, 4, 1, 5, 9, 2]
numbers.sort()
print(f"sort 후 숫자 리스트: {numbers}")

# reverse(): 리스트의 요소 순서를 뒤집습니다 (제자리 뒤집기).
my_list.reverse()
print(f"reverse 후 리스트: {my_list}")

'apple'의 인덱스: 2
'apple'의 개수: 2
sort 후 숫자 리스트: [1, 1, 2, 3, 4, 5, 9]
reverse 후 리스트: ['apple', 'elderberry', 'date', 'cherry', 'banana', 'apple', 'blueberry', 1]


In [10]:
# 빈칸 채우기 실습

# 1. 아래 빈칸을 채워 과일 이름 세 개를 포함하는 리스트 `fruits`를 만드세요.
fruits = ['apple', 'banana', ______]
print(f"원래 리스트: {fruits}")

# 2. `fruits` 리스트의 끝에 'grape'를 추가하는 코드를 작성하세요.
fruits.______(______)
print(f"요소 추가 후 리스트: {fruits}")

# 3. `fruits` 리스트에서 두 번째 요소('banana')를 인덱싱을 사용하여 출력하는 코드를 작성하세요.
second_fruit = fruits[______]
print(f"두 번째 요소: {second_fruit}")

# 4. `fruits` 리스트에서 'apple'과 'banana'를 포함하는 슬라이스를 추출하여 `first_two` 변수에 저장하세요.
first_two = fruits[______:______]
print(f"처음 두 요소: {first_two}")

원래 리스트: ['apple', 'banana', <function ______ at 0x79d5b3d26e80>]


AttributeError: 'list' object has no attribute '______'

# 3. 딕셔너리 (Dictionaries)

딕셔너리는 순서가 없는(unordered) 키-값(key-value) 쌍의 모음입니다.

각 키는 고유해야 하며, 값을 조회하거나 변경할 때 사용됩니다.

In [11]:
# 딕셔너리 생성
# 중괄호 {}를 사용하며, 각 요소는 '키: 값' 형태로 쉼표로 구분됩니다.
my_dict = {'apple': 1, 'banana': 2, 'cherry': 3}
print(f"새로 생성된 딕셔너리: {my_dict}")

# 빈 딕셔너리 생성
empty_dict = {}
print(f"빈 딕셔너리: {empty_dict}")

새로 생성된 딕셔너리: {'apple': 1, 'banana': 2, 'cherry': 3}
빈 딕셔너리: {}


In [12]:
# 키-값 접근 (Accessing Values)

# 키를 사용하여 해당 값에 접근할 수 있습니다.
apple_value = my_dict['apple']
print(f"'apple' 키의 값: {apple_value}")

# 존재하지 않는 키에 접근하면 KeyError가 발생합니다.
# print(my_dict['grape']) # KeyError 발생

# .get() 메서드를 사용하면 키가 없을 때 None 또는 기본값을 반환합니다.
grape_value = my_dict.get('grape')
print(f"'grape' 키의 값 (.get() 사용): {grape_value}")

grape_value_default = my_dict.get('grape', 'Not Found')
print(f"'grape' 키의 값 (.get() 기본값 사용): {grape_value_default}")

# 키를 사용하여 값을 변경하거나 새 키-값 쌍을 추가할 수 있습니다.
my_dict['banana'] = 20
print(f"'banana' 값 변경 후: {my_dict}")

my_dict['date'] = 4
print(f"'date' 키-값 추가 후: {my_dict}")

'apple' 키의 값: 1
'grape' 키의 값 (.get() 사용): None
'grape' 키의 값 (.get() 기본값 사용): Not Found
'banana' 값 변경 후: {'apple': 1, 'banana': 20, 'cherry': 3}
'date' 키-값 추가 후: {'apple': 1, 'banana': 20, 'cherry': 3, 'date': 4}


In [13]:
# 딕셔너리 메서드 (1) (Dictionary Methods)

# keys(): 딕셔너리의 모든 키를 포함하는 뷰(view) 객체를 반환합니다.
keys_view = my_dict.keys()
print(f"모든 키: {keys_view}")
# 리스트로 변환할 수 있습니다.
print(f"모든 키 (리스트): {list(keys_view)}")

# values(): 딕셔너리의 모든 값을 포함하는 뷰 객체를 반환합니다.
values_view = my_dict.values()
print(f"모든 값: {values_view}")
print(f"모든 값 (리스트): {list(values_view)}")

# items(): 딕셔너리의 모든 키-값 쌍을 (키, 값) 튜플의 뷰 객체로 반환합니다.
items_view = my_dict.items()
print(f"모든 키-값 쌍: {items_view}")
print(f"모든 키-값 쌍 (리스트): {list(items_view)}")

모든 키: dict_keys(['apple', 'banana', 'cherry', 'date'])
모든 키 (리스트): ['apple', 'banana', 'cherry', 'date']
모든 값: dict_values([1, 20, 3, 4])
모든 값 (리스트): [1, 20, 3, 4]
모든 키-값 쌍: dict_items([('apple', 1), ('banana', 20), ('cherry', 3), ('date', 4)])
모든 키-값 쌍 (리스트): [('apple', 1), ('banana', 20), ('cherry', 3), ('date', 4)]


In [14]:
# 딕셔너리 메서드 (2) (Dictionary Methods)

# pop(key[, default]): 특정 키의 항목을 제거하고 해당 값을 반환합니다. 키가 없으면 KeyError 또는 default 값을 반환합니다.
popped_value = my_dict.pop('cherry')
print(f"pop으로 제거된 값 ('cherry'): {popped_value}")
print(f"pop 후 딕셔너리: {my_dict}")

# popitem(): 딕셔너리의 마지막 항목(Python 3.7+에서는 삽입 순서에 따라)을 제거하고 (키, 값) 튜플로 반환합니다.
popped_item = my_dict.popitem()
print(f"popitem으로 제거된 항목: {popped_item}")
print(f"popitem 후 딕셔너리: {my_dict}")

# clear(): 딕셔너리의 모든 항목을 제거합니다.
# my_dict.clear()
# print(f"clear 후 딕셔너리: {my_dict}")

# len(): 딕셔너리의 항목(키-값 쌍) 개수를 반환합니다.
dict_length = len(my_dict)
print(f"딕셔너리의 길이: {dict_length}")

pop으로 제거된 값 ('cherry'): 3
pop 후 딕셔너리: {'apple': 1, 'banana': 20, 'date': 4}
popitem으로 제거된 항목: ('date', 4)
popitem 후 딕셔너리: {'apple': 1, 'banana': 20}
딕셔너리의 길이: 2


In [15]:
# 빈칸 채우기 실습

# 1. 아래 빈칸을 채워 이름과 나이를 키-값으로 갖는 딕셔너리 `person`을 만드세요.
# person = {'name': '______', 'age': ______} # 예: {'name': 'Alice', 'age': 30}
# print(f"생성된 딕셔너리: {person}")

# 2. `person` 딕셔너리에서 'name' 키의 값을 인덱싱을 사용하여 출력하는 코드를 작성하세요.
# person_name = person[______] # 예: person_name = person['name']
# print(f"이름: {person_name}")

# 3. `person` 딕셔너리에 'city' 키와 값 ('Seoul')을 추가하는 코드를 작성하세요.
# person[______] = ______ # 예: person['city'] = 'Seoul'
# print(f"도시 추가 후 딕셔너리: {person}")

# 4. `person` 딕셔너리의 모든 키를 리스트 형태로 출력하는 코드를 작성하세요.
# keys_list = list(person.______) # 예: keys_list = list(person.keys())
# print(f"모든 키: {keys_list}")

# 4. 넘파이 기초 (NumPy Basics)

NumPy는 파이썬에서 과학 계산, 특히 수치 계산을 효율적으로 수행하기 위한 핵심 라이브러리입니다.

다차원 배열(ndarray) 객체를 지원하며, 벡터 및 행렬 연산에 최적화되어 있습니다.

빅데이터 분석 및 머신러닝 분야에서 데이터 처리에 필수적으로 사용됩니다.

In [16]:
# NumPy 라이브러리 Import
# 일반적으로 np라는 별칭으로 import 합니다.
import numpy as np
print("NumPy 라이브러리 import 완료.")

NumPy 라이브러리 import 완료.


In [18]:
# 넘파이 배열 생성 (1)

# 파이썬 리스트로부터 배열 생성
python_list = [1, 2, 3, 4, 5]
numpy_array_from_list = np.array(python_list)
print(f"\n파이썬 리스트로 생성된 배열: {numpy_array_from_list}")

# 특정 값으로 채워진 배열 생성 (zeros, ones, empty)
zeros_array = np.zeros((2, 3)) # 2x3 크기의 0으로 채워진 배열
print(f"\n0으로 채워진 배열 (2x3):\n{zeros_array}")


파이썬 리스트로 생성된 배열: [1 2 3 4 5]

0으로 채워진 배열 (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# 넘파이 배열 생성 (2)

ones_array = np.ones((3, 2)) # 3x2 크기의 1로 채워진 배열
print(f"\n1로 채워진 배열 (3x2):\n{ones_array}")

empty_array = np.empty((2, 2)) # 초기화되지 않은 배열 (임의의 값 포함)
print(f"\n초기화되지 않은 배열 (2x2):\n{empty_array}")


1로 채워진 배열 (3x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]]

초기화되지 않은 배열 (2x2):
[[0.25 0.5 ]
 [0.75 1.  ]]


In [21]:
# 범위 값으로 배열 생성 (arange, linspace)
range_array = np.arange(10) # 0부터 9까지 (10 미만) 정수 배열
print(f"\narange로 생성된 배열 (0-9): {range_array}")

range_step_array = np.arange(0, 10, 2) # 0부터 10 미만까지 2씩 증가하는 배열
print(f"arange로 생성된 배열 (0-10, step 2): {range_step_array}")

linspace_array = np.linspace(0, 1, 5) # 0부터 1까지 5개의 등간격 점으로 이루어진 배열
print(f"linspace로 생성된 배열 (0-1, 5점): {linspace_array}")


arange로 생성된 배열 (0-9): [0 1 2 3 4 5 6 7 8 9]
arange로 생성된 배열 (0-10, step 2): [0 2 4 6 8]
linspace로 생성된 배열 (0-1, 5점): [0.   0.25 0.5  0.75 1.  ]


In [22]:
# 기본 연산 (Basic Operations)

# 배열 간 연산 (요소별 연산)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b
multiplication = a * b # 요소별 곱셈 (행렬 곱셈이 아님)
division = a / b

print(f"\n배열 a: {a}")
print(f"배열 b: {b}")
print(f"a + b: {addition}")
print(f"a - b: {subtraction}")
print(f"a * b (요소별 곱셈): {multiplication}")
print(f"a / b: {division}")


배열 a: [1 2 3]
배열 b: [4 5 6]
a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b (요소별 곱셈): [ 4 10 18]
a / b: [0.25 0.4  0.5 ]


In [23]:
# 배열과 스칼라 간 연산
scalar = 10
array_scalar_addition = a + scalar
array_scalar_multiplication = a * scalar

print(f"\n배열 a: {a}")
print(f"스칼라: {scalar}")
print(f"a + scalar: {array_scalar_addition}")
print(f"a * scalar: {array_scalar_multiplication}")


배열 a: [1 2 3]
스칼라: 10
a + scalar: [11 12 13]
a * scalar: [10 20 30]


In [24]:
# shape: 배열의 각 차원의 크기를 튜플 형태로 반환합니다.
array_shape = numpy_array_from_list.shape
matrix_shape = zeros_array.shape
print(f"\nnumpy_array_from_list의 shape: {array_shape}")
print(f"zeros_array의 shape: {matrix_shape}")


numpy_array_from_list의 shape: (5,)
zeros_array의 shape: (2, 3)


In [26]:
# dtype: 배열 요소의 데이터 타입을 반환합니다.
array_dtype = numpy_array_from_list.dtype
float_dtype = zeros_array.dtype
print(f"numpy_array_from_list의 dtype: {array_dtype}")
print(f"zeros_array의 dtype: {float_dtype}")

numpy_array_from_list의 dtype: int32
zeros_array의 dtype: float64


In [27]:
# 데이터 타입 지정하여 배열 생성
int_array = np.array([1, 2, 3], dtype=np.int64)
float_array = np.array([1.0, 2.5, 3.1], dtype=np.float32)
print(f"\nint_array (dtype=int64): {int_array}, dtype: {int_array.dtype}")
print(f"float_array (dtype=float32): {float_array}, dtype: {float_array.dtype}")


int_array (dtype=int64): [1 2 3], dtype: int64
float_array (dtype=float32): [1.  2.5 3.1], dtype: float32


In [28]:
# 간단한 통계 계산

# 넘파이 배열은 대규모 데이터셋에 대한 빠르고 효율적인 통계 계산을 지원합니다.
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [29]:
# 평균 (Mean)
mean_value = np.mean(data) # 또는 data.mean()
print(f"\n데이터 배열: {data}")
print(f"평균: {mean_value}")


데이터 배열: [ 10  20  30  40  50  60  70  80  90 100]
평균: 55.0


In [30]:
# 합계 (Sum)
sum_value = np.sum(data) # 또는 data.sum()
print(f"합계: {sum_value}")

합계: 550


In [31]:
# 최소값 (Minimum)
min_value = np.min(data) # 또는 data.min()
print(f"최소값: {min_value}")

# 최대값 (Maximum)
max_value = np.max(data) # 또는 data.max()
print(f"최대값: {max_value}")

최소값: 10
최대값: 100


In [32]:
# 표준 편차 (Standard Deviation)
std_dev = np.std(data) # 또는 data.std()
print(f"표준 편차: {std_dev}")

# 분산 (Variance)
variance = np.var(data) # 또는 data.var()
print(f"분산: {variance}")

표준 편차: 28.722813232690143
분산: 825.0


In [33]:
# 다차원 배열 통계 (예: 행렬)
matrix_data = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n행렬 데이터:\n{matrix_data}")


행렬 데이터:
[[1 2 3]
 [4 5 6]]


In [34]:
# 전체 평균
overall_mean = np.mean(matrix_data)
print(f"전체 평균: {overall_mean}")

전체 평균: 3.5


In [35]:
# 축(axis)을 따라 통계 계산
# axis=0: 열을 따라 계산 (각 열의 통계)
mean_per_column = np.mean(matrix_data, axis=0)
print(f"열별 평균 (axis=0): {mean_per_column}")

열별 평균 (axis=0): [2.5 3.5 4.5]


In [36]:
# axis=1: 행을 따라 계산 (각 행의 통계)
mean_per_row = np.mean(matrix_data, axis=1)
print(f"행별 평균 (axis=1): {mean_per_row}")

행별 평균 (axis=1): [2. 5.]


In [19]:
# 빈칸 채우기 실습

# 1. 아래 빈칸을 채워 NumPy 라이브러리를 `np`로 import 하세요.
# ______ numpy as ______

# 2. 아래 빈칸을 채워 파이썬 리스트 `[10, 20, 30, 40, 50]`를 넘파이 배열 `my_numpy_array`로 만드세요.
python_list_for_exercise = [10, 20, 30, 40, 50]
# my_numpy_array = ______.array(______)
# print(f"넘파이 배열: {my_numpy_array}")

# 3. 아래 빈칸을 채워 3x3 크기의 1로 채워진 넘파이 배열 `ones_matrix`를 만드세요.
# ones_matrix = np.______(______)
# print(f"\n1로 채워진 행렬:\n{ones_matrix}")

# 4. 두 넘파이 배열 `arr1`과 `arr2`의 요소별 덧셈 결과를 계산하여 `sum_array` 변수에 저장하고 출력하세요.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# sum_array = ______ ______ ______
# print(f"\n덧셈 결과: {sum_array}")

# 5. 넘파이 배열 `data_for_stats`의 평균값을 계산하여 출력하세요.
data_for_stats = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# mean_of_data = np.______(______) # 또는 data_for_stats.______()
# print(f"\n데이터의 평균: {mean_of_data}")

# Note: The lines with '#' at the beginning are the lines for the user to fill in.
# The examples are provided as comments where helpful.

# 5. 종합 실습 (Integrated Practice)

이 섹션에서는 앞에서 학습한 리스트, 딕셔너리, 넘파이의 개념을 활용하여 간단한 데이터 처리 실습을 진행합니다.

특히, 빅데이터 분석에서 자주 사용되는 데이터 그룹화 및 필터링 기법을 익힙니다.

In [37]:
# 데이터 준비: 학생들의 과목별 점수 데이터 (리스트와 딕셔너리 활용)
# 각 딕셔너리는 한 학생의 정보를 나타내며, 리스트에 저장됩니다.
student_scores = [
    {'name': '김철수', 'subject': '수학', 'score': 85},
    {'name': '이영희', 'subject': '영어', 'score': 92},
    {'name': '박찬호', 'subject': '수학', 'score': 78},
    {'name': '김철수', 'subject': '영어', 'score': 88},
    {'name': '이영희', 'subject': '수학', 'score': 95},
    {'name': '박찬호', 'subject': '영어', 'score': 80},
    {'name': '김철수', 'subject': '수학', 'score': 90}
]

print("원본 학생 점수 데이터:")
display(student_scores)

원본 학생 점수 데이터:


[{'name': '김철수', 'subject': '수학', 'score': 85},
 {'name': '이영희', 'subject': '영어', 'score': 92},
 {'name': '박찬호', 'subject': '수학', 'score': 78},
 {'name': '김철수', 'subject': '영어', 'score': 88},
 {'name': '이영희', 'subject': '수학', 'score': 95},
 {'name': '박찬호', 'subject': '영어', 'score': 80},
 {'name': '김철수', 'subject': '수학', 'score': 90}]

In [38]:
# 빅데이터 분석 연계 (1): 딕셔너리를 이용한 데이터 그룹화
# 과목별로 점수를 그룹화합니다. 이는 대규모 데이터셋에서 특정 기준별로 데이터를 집계할 때 유용합니다.
scores_by_subject = {}

for record in student_scores:
    subject = record['subject']
    score = record['score']

    if subject not in scores_by_subject:
        scores_by_subject[subject] = [] # 해당 과목의 리스트가 없으면 새로 생성
    scores_by_subject[subject].append(score) # 해당 과목 리스트에 점수 추가

print("\n과목별로 그룹화된 점수:")
display(scores_by_subject)


과목별로 그룹화된 점수:


{'수학': [85, 78, 95, 90], '영어': [92, 88, 80]}

In [39]:
# 그룹화된 데이터에 대한 간단한 통계 계산 (NumPy 활용)
print("\n과목별 평균 점수 (NumPy 활용):")
for subject, scores in scores_by_subject.items():
    # 리스트를 넘파이 배열로 변환하여 통계 계산 효율성 높이기
    np_scores = np.array(scores)
    average_score = np.mean(np_scores)
    print(f"{subject}: {average_score:.2f}")


과목별 평균 점수 (NumPy 활용):
수학: 87.00
영어: 86.67


In [40]:
# 빅데이터 분석 연계 (2): 리스트 컴프리헨션을 이용한 데이터 필터링
# 특정 기준(예: 점수 85점 이상)을 만족하는 데이터만 추출합니다.
# 이는 대규모 데이터셋에서 필요한 정보만 빠르게 골라낼 때 효과적입니다.
high_scores = [
    record for record in student_scores if record['score'] >= 85
]

print("\n점수 85점 이상인 데이터 (리스트 컴프리헨션 활용):")
display(high_scores)

# 이름이 '김철수'인 학생의 데이터만 필터링
kim_chulsoo_scores = [
    record for record in student_scores if record['name'] == '김철수'
]

print("\n'김철수' 학생의 데이터:")
display(kim_chulsoo_scores)


점수 85점 이상인 데이터 (리스트 컴프리헨션 활용):


[{'name': '김철수', 'subject': '수학', 'score': 85},
 {'name': '이영희', 'subject': '영어', 'score': 92},
 {'name': '김철수', 'subject': '영어', 'score': 88},
 {'name': '이영희', 'subject': '수학', 'score': 95},
 {'name': '김철수', 'subject': '수학', 'score': 90}]


'김철수' 학생의 데이터:


[{'name': '김철수', 'subject': '수학', 'score': 85},
 {'name': '김철수', 'subject': '영어', 'score': 88},
 {'name': '김철수', 'subject': '수학', 'score': 90}]

In [41]:
# 필터링된 데이터에 대한 넘파이 통계 계산
# '김철수' 학생의 점수만 추출하여 평균 계산
kim_chulsoo_score_list = [record['score'] for record in kim_chulsoo_scores]
if kim_chulsoo_score_list: # 리스트가 비어있지 않은 경우에만 계산
    np_kim_chulsoo_scores = np.array(kim_chulsoo_score_list)
    avg_kim_chulsoo = np.mean(np_kim_chulsoo_scores)
    print(f"\n'김철수' 학생의 평균 점수: {avg_kim_chulsoo:.2f}")
else:
    print("\n'김철수' 학생 데이터가 없습니다.")


'김철수' 학생의 평균 점수: 87.67


In [23]:
# 종합 실습 - 빈칸 채우기

# 다음은 학생들의 성적 데이터를 처리하는 코드입니다.
# 리스트, 딕셔너리, 넘파이를 활용하여 주어진 문제를 해결하는 빈칸을 채우세요.

student_data = [
    {'id': 1, 'name': 'Alice', 'major': 'CS', 'gpa': 3.8},
    {'id': 2, 'name': 'Bob', 'major': 'EE', 'gpa': 3.5},
    {'id': 3, 'name': 'Charlie', 'major': 'CS', 'gpa': 4.0},
    {'id': 4, 'name': 'David', 'major': 'ME', 'gpa': 3.2},
    {'id': 5, 'name': 'Eve', 'major': 'CS', 'gpa': 3.9}
]

# 1. `student_data` 리스트의 길이를 확인하고 출력하세요.
# data_length = ______
# print(f"총 학생 수: {data_length}")

# 2. 첫 번째 학생의 딕셔너리에서 'name'과 'gpa' 값을 추출하여 출력하세요.
# first_student = ______
# first_student_name = first_student[______]
# first_student_gpa = first_student[______]
# print(f"첫 번째 학생 이름: {first_student_name}, GPA: {first_student_gpa}")

# 3. 모든 학생의 GPA 값만 추출하여 리스트 `gpa_list`를 만드세요. (리스트 컴프리헨션 활용)
# gpa_list = [______ for ______ in ______]
# print(f"모든 학생의 GPA 리스트: {gpa_list}")

# 4. `gpa_list`를 넘파이 배열 `gpa_np_array`로 변환하고, 이 배열의 평균 GPA를 계산하여 출력하세요.
# gpa_np_array = np.______(______)
# average_gpa = np.______(______) # 또는 gpa_np_array.______()
# print(f"평균 GPA: {average_gpa:.2f}")

# 5. 전공(major)이 'CS'인 학생들의 데이터만 필터링하여 새로운 리스트 `cs_students`를 만드세요. (리스트 컴프리헨션 활용)
# cs_students = [
#     ______ for ______ in ______ if ______ == 'CS'
# ]
# print(f"\nCS 전공 학생 데이터:")
# display(cs_students)

# 6. `cs_students` 리스트에서 CS 전공 학생들의 GPA만 추출하여 평균 GPA를 계산하세요. (리스트 컴프리헨션 및 넘파이 활용)
# cs_gpas = [______ for ______ in ______]
# cs_average_gpa = np.mean(______)
# print(f"CS 전공 학생들의 평균 GPA: {cs_average_gpa:.2f}")

# Note: The lines with '#' at the beginning are the lines for the user to fill in.